### ISSUE TITLE
Mainboard link is 404

### ISSUE THREAD

**Issue by meron1122** [goat-hill/bitclock#6]
Hi, mainboard link from readme.md causes 404.

**Comment by babldev** [comment]
I went ahead and uploaded the rev3a design today https://github.com/goat-hill/bitclock/tree/master/bitclock-pcb/rev3a

I wasn't sure if I wanted to immediately open source the PCB design until I finished selling a first batch here https://bitclock.io/order

But given I don't ship outside of the USA so I don't have to work through the regulatory stuff I decided to open source it in case others want to order! I included ordering files from JLCPCB.
